Repository UKS-2023-2024/WEB-API, pull requests merged in 2023-11, with the labels that each got.

#27 Feature/update and delete profile
  Application/Auth/Commands/Delete/DeleteUserCommand.cs
  Application/Auth/Commands/Delete/DeleteUserCommandHandler.cs
  Application/Auth/Commands/Update/UpdateUserCommand.cs
  Application/Auth/Commands/Update/UpdateUserCommandHandler.cs
  Domain/Auth/Interfaces/ISocialAccountRepository.cs
  Domain/Auth/User.cs
  Infrastructure/Auth/Repositories/SocialAccountRepository.cs
  Infrastructure/Auth/Repositories/UserRepository.cs
  Infrastructure/DependencyInjection.cs
  Tests/Integration/Auth/AuthIntegrationTest.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/DeleteUserUnitTests.cs
  Tests/Unit/UpdateUserUnitTests.cs
  WebApi/Auth/AuthController.cs
  WebApi/Auth/Dtos/CurrentUserDto.cs
  WebApi/Auth/Dtos/UpdateUserDto.cs
Labels: enhancement

#54 added initial uml diagram
  UKS-uml-diagram.puml
Labels: documentation

#71 Bugfix/changing email implementation from sendgrid to email
  .github/workflows/dotnet.yml
  Application/Organizations/Commands/SendInvite/SendInviteCommandHandler.cs
  Application/Organizations/Events/MemberInvited/OrganizationMemberInvitedEventHandler.cs
  Application/Repositories/Commands/HandleRepositoryMembers/SendRepositoryInvite/SendInviteCommandHandler.cs
  Application/Repositories/Events/MemberInvited/RepositoryMemberInvitedEventHandler.cs
  Domain/Repositories/Interfaces/IRepositoryInviteRepository.cs
  Domain/Shared/Interfaces/IEmailService.cs
  Infrastructure/DependencyInjection.cs
  Infrastructure/Organizations/Repositories/OrganizationInviteRepository.cs
  Infrastructure/Repositories/Repositories/RepositoryInviteRepository.cs
  Infrastructure/Shared/Email/GmailEmailService.cs
  Infrastructure/Shared/Email/SendgridEmailService.cs
  WebApi/Dockerfile
  WebApi/Repositories/RepositoryController.cs
  WebApi/appsettings.json
Labels: bug

#67 Feature/edit branch
  Application/Branches/Commands/Update/MakeDefault/MakeBranchDefaultCommand.cs
  Application/Branches/Commands/Update/MakeDefault/MakeBranchDefaultCommandHandler.cs
  Application/Branches/Commands/Update/UpdateName/UpdateBranchNameCommand.cs
  Application/Branches/Commands/Update/UpdateName/UpdateBranchNameCommandHandler.cs
  Domain/Branches/Branch.cs
  Domain/Branches/Exceptions/BranchIsAlreadyDefaultException.cs
  Domain/Branches/Exceptions/BranchNotFoundException.cs
  Domain/Branches/Interfaces/IBranchRepository.cs
  Infrastructure/Branches/BranchRepository.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/Branches/MakeBranchDefaultUnitTests.cs
  Tests/Unit/Branches/UpdateBranchNameUnitTests.cs
  WebApi/Branches/BranchController.cs
  WebApi/Branches/Dtos/UpdateBranchDto.cs
Labels: enhancement

#69 Feature/restore branch
  Application/Branches/Commands/Restore/RestoreBranchCommand.cs
  Application/Branches/Commands/Restore/RestoreBranchCommandHandler.cs
  Domain/Branches/Branch.cs
  Tests/Unit/Branches/RestoreBranchUnitTests.cs
  WebApi/Branches/BranchController.cs
Labels: enhancement

#74 Feature/fetch repository branches
  Application/Application.csproj
  Application/Branches/Commands/Update/MakeDefault/MakeBranchDefaultCommandHandler.cs
  Application/Branches/Queries/FindAllUserWithoutDefaultByRepositoryId/FindAllUserBranchesWithoutDefaultByRepositoryIdQuery.cs
  Application/Branches/Queries/FindAllUserWithoutDefaultByRepositoryId/FindAllUserBranchesWithoutDefaultByRepositoryIdQueryHandler.cs
  Application/Branches/Queries/FindAllWithoutDefaultByRepositoryId/FindAllBranchesWithoutDefaultByRepositoryIdQuery.cs
  Application/Branches/Queries/FindAllWithoutDefaultByRepositoryId/FindAllBranchesWithoutDefaultByRepositoryIdQueryHandler.cs
  Application/Branches/Queries/FindAllWithoutDefaultByRepositoryIdPagination/FindAllBranchesWithoutDefaultByRepositoryIdPaginationQuery.cs
  Application/Branches/Queries/FindAllWithoutDefaultByRepositoryIdPagination/FindAllBranchesWithoutDefaultByRepositoryIdPaginationQueryHandler.cs
  Application/Branches/Queries/FindDefaultBranchByRepositoryId/FindDefaultBranchByRepositoryIdQuery.cs
  Application/Branches/Queries/FindDefaultBranchByRepositoryId/FindDefultBranchByRepositoryIdQueryHandler.cs
  Application/Repositories/Commands/Create/CreateForOrganization/CreateRepositoryForOrganizationCommandHandler.cs
  Application/Repositories/Commands/Create/CreateForUser/CreateRepositoryForUserCommandHandler.cs
  Domain/Branches/Branch.cs
  Domain/Branches/Interfaces/IBranchRepository.cs
  Domain/Repositories/Repository.cs
  Domain/Shared/PagedResult.cs
  Infrastructure/Branches/BranchRepository.cs
  Tests/Unit/Branches/FindAllBranchesUnitTests.cs
  WebApi/Branches/BranchController.cs
  WebApi/Branches/Dtos/UpdateBranchDto.cs
  WebApi/ExceptionHandling/ExceptionHandler.cs
Labels: enhancement

#79 added finding member role for repository and fixed problem with leavi…
  Application/Repositories/Commands/HandleRepositoryMembers/AddRepositoryMember/AddRepositoryMemberCommand.cs
  Application/Repositories/Commands/HandleRepositoryMembers/AddRepositoryMember/AddRepositoryMemberCommandHandler.cs
  Application/Repositories/Commands/HandleRepositoryMembers/RemoveRepositoryMember/RemoveRepositoryMemberCommandHandler.cs
  Application/Repositories/Queries/FindRepositoryMemberRole/FindRepositoryMemberRoleQuery.cs
  Application/Repositories/Queries/FindRepositoryMemberRole/FindRepositoryMemberRoleQueryHandler.cs
  Domain/Repositories/Exceptions/RepositoryMemberCantBeDeletedException.cs
  Domain/Repositories/Interfaces/IRepositoryMemberRepository.cs
  Infrastructure/Repositories/Repositories/RepositoryMemberRepository.cs
  Infrastructure/Repositories/Repositories/RepositoryRepository.cs
  Tests/Integration/Repositories/RemoveRepositoryMemberIntegrationTest.cs
  Tests/Unit/Repositories/AddRepositoryMemberUnitTests.cs
  Tests/Unit/Repositories/RemoveRepositoryMemberUnitTests.cs
  WebApi/ExceptionHandling/ExceptionHandler.cs
  WebApi/Repositories/Presenters/RepositoryMemberPresenter.cs
  WebApi/Repositories/RepositoryController.cs
Labels: bug, enhancement

#84 Bugfix/problem with repository being left without owner
  Application/Repositories/Commands/HandleRepositoryMembers/ChangeRole/ChangeMemberRoleCommandHandler.cs
  Application/Repositories/Commands/HandleRepositoryMembers/RemoveRepositoryMember/RemoveRepositoryMemberCommandHandler.cs
  Domain/Repositories/Exceptions/RepositoryMemberCantBeChangedException.cs
  Domain/Repositories/Exceptions/RepositoryMemberCantBeDeletedException.cs
  Domain/Repositories/Exceptions/RepositoryMemberCantChangeHimselfException.cs
  Domain/Repositories/RepositoryMember.cs
  Tests/Integration/Repositories/ChangeRepositoryMemberRoleIntegrationTest.cs
  Tests/Integration/Repositories/DidUserStarRepositoryIntegrationTest.cs
  Tests/Integration/Repositories/FindAllRepositoryMembersIntegrationTest.cs
  Tests/Integration/Repositories/FindAllUsersThatStarredIntegrationTest.cs
  Tests/Integration/Repositories/RemoveRepositoryMemberIntegrationTest.cs
  Tests/Integration/Repositories/SendRepositoryInviteIntegrationTest.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/Repositories/ChangeRepositoryMemberRoleUnitTests.cs
  Tests/Unit/Repositories/RemoveRepositoryMemberUnitTests.cs
  WebApi/ExceptionHandling/ExceptionHandler.cs
Labels: bug
