Repository UKS-2023-2024/WEB-API, pull requests merged in 2024-02, with the labels that each got.

#144 Added file tree endpoint
  Application/Branches/Queries/ListBranchFiles/ListBranchFilesQuery.cs
  Application/Branches/Queries/ListBranchFiles/ListBranchFilesQueryHandler.cs
  Domain/Branches/Branch.cs
  Domain/Branches/ContributionFile.cs
  Domain/Branches/Interfaces/IBranchRepository.cs
  Domain/Shared/Git/Payloads/FileInformation.cs
  Domain/Shared/Interfaces/IGitService.cs
  Infrastructure/Branches/BranchRepository.cs
  Infrastructure/Shared/Git/GiteaService.cs
  WebApi/Branches/BranchController.cs
Labels: enhancement

#152 Feature/milestone progress bar
  Application/Milestones/Queries/FindCompletionPercentageOfMilestone/FindCompletionPercentageOfMilestoneQuery.cs
  Application/Milestones/Queries/FindCompletionPercentageOfMilestone/FindCompletionPercentageOfMilestoneQueryHandler.cs
  Domain/Tasks/Interfaces/IIssueRepository.cs
  Infrastructure/Tasks/IssueRepository.cs
  Tests/Integration/Milestones/FindMilestoneCompletionPercentageIntegrationTest.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/Milestones/FindMilestoneCompletionPercentageUnitTests.cs
  WebApi/Milestones/MilestoneController.cs
  WebApi/Milestones/Presenters/MilestonePresenter.cs
  WebApi/appsettings.json
Labels: enhancement

#160 Feature/close reopen pr
  Application/Issues/Commands/Close/CloseIssueCommandHandler.cs
  Application/Issues/Commands/Reopen/ReopenIssueCommandHandler.cs
  Application/PullRequests/Commands/Close/ClosePullRequestCommand.cs
  Application/PullRequests/Commands/Close/ClosePullRequestCommandHandler.cs
  Application/PullRequests/Commands/Reopen/ReopenPullRequestCommand.cs
  Application/PullRequests/Commands/Reopen/ReopenPullRequestCommandHandler.cs
  Application/PullRequests/Queries/FindPullRequest/FindPullRequestQuery.cs
  Application/PullRequests/Queries/FindPullRequest/FindPullRequestQueryHandler.cs
  Application/PullRequests/Queries/FindPullRequestEvents/FindPullRequestEventsQuery.cs
  Application/PullRequests/Queries/FindPullRequestEvents/FindPullRequestEventsQueryHandler.cs
  Domain/Tasks/CloseEvent.cs
  Domain/Tasks/Event.cs
  Domain/Tasks/PullRequest.cs
  Domain/Tasks/PullRequestMergedEvent.cs
  Infrastructure/Configuration/EventConfiguration.cs
  Infrastructure/Migrations/MainDbContextModelSnapshot.cs
  Infrastructure/Notifications/Services/NotificationService.cs
  Infrastructure/Repositories/Repositories/RepositoryMemberRepository.cs
  Infrastructure/Tasks/IssueRepository.cs
  Infrastructure/Tasks/PullRequestRepository.cs
  Tests/Integration/PullRequests/ClosePullRequestIntegrationTests.cs
  Tests/Integration/PullRequests/ReopenPullRequestIntegrationTests.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/PullRequests/ClosePullRequestUnitTests.cs
  Tests/Unit/PullRequests/ReopenPullRequestUnitTests.cs
  WebApi/Tasks/PullRequestController.cs
Labels: enhancement

#168 Feature/unassign milestone from pr
  Application/Application.csproj
  Application/PullRequests/Commands/IssueAssignment/AssignIssuesToPullRequestCommand.cs
  Application/PullRequests/Commands/IssueAssignment/AssignIssuesToPullRequestCommandHandler.cs
  Application/PullRequests/Commands/MilestoneAssignment/AssignMilestoneToPullRequestCommand.cs
  Application/PullRequests/Commands/MilestoneAssignment/AssignMilestoneToPullRequestCommandHandler.cs
  Application/PullRequests/Commands/MilestoneUnassignment/UnassignMilestoneFromPullRequestCommand.cs
  Application/PullRequests/Commands/MilestoneUnassignment/UnassignMilestoneFromPullRequestCommandHandler.cs
  Domain/Tasks/Issue.cs
  Domain/Tasks/PullRequest.cs
  Infrastructure/Tasks/PullRequestRepository.cs
  Tests/Integration/PullRequests/AssignIssuesToPullRequestIntegrationTests.cs
  Tests/Integration/PullRequests/AssignMilestoneToPullRequestIntegrationTests.cs
  Tests/Integration/PullRequests/UnassignMilestoneFromPullRequestIntegrationTests.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/PullRequests/AssignIssuesToPullRequestUnitTests.cs
  Tests/Unit/PullRequests/AssignMilestoneToPullRequestUnitTests.cs
  Tests/Unit/PullRequests/UnassignMilestoneToPullRequestUnitTests.cs
  WebApi/Tasks/Dtos/UpdatePullRequestDto.cs
  WebApi/Tasks/PullRequestController.cs
Labels: enhancement

#170 Feature/merge pull request
  Application/Issues/Commands/Create/CreateIssueCommandHandler.cs
  Application/PullRequests/Commands/CreatePullRequest/CreatePullRequestCommandHandler.cs
  Application/PullRequests/Commands/Merge/MergePullRequestCommand.cs
  Application/PullRequests/Commands/Merge/MergePullRequestCommandHandler.cs
  Domain/Shared/Git/Payloads/GitPullRequest.cs
  Domain/Shared/Interfaces/IGitService.cs
  Domain/Tasks/Enums/MergeType.cs
  Domain/Tasks/Interfaces/IPullRequestRepository.cs
  Domain/Tasks/Interfaces/ITaskRepository.cs
  Infrastructure/Shared/Git/GiteaService.cs
  Infrastructure/Tasks/PullRequestRepository.cs
  Infrastructure/Tasks/TaskRepository.cs
  Tests/Integration/PullRequests/MergePullRequestIntegrationTests.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/Issues/CreateIssueUnitTests.cs
  Tests/Unit/PullRequests/CreatePullRequestsUnitTests.cs
  Tests/Unit/PullRequests/MergePullRequestUnitTests.cs
  WebApi.sln.DotSettings.user
  WebApi/Tasks/PullRequestController.cs
Labels: enhancement

#184 Bugfix/create pr
  Application/Issues/Commands/Update/UpdateIssueCommandHandler.cs
  Application/PullRequests/Commands/LabelAssignment/AssignLabelsToPullRequestCommand.cs
  Application/PullRequests/Commands/LabelAssignment/AssignLabelsToPullRequestCommandHandler.cs
  Application/PullRequests/Commands/UserAssignment/AssignUsersToPullRequestCommandHandler.cs
  Domain/Tasks/PullRequest.cs
  Infrastructure/Tasks/PullRequestRepository.cs
  Tests/Integration/PullRequests/AssignLabelsToPullRequestIntegrationTests.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/PullRequests/AssignLabelsToPullRequestUnitTests.cs
  WebApi/Tasks/Dtos/UpdatePullRequestDto.cs
  WebApi/Tasks/Presenters/LabelPresenter.cs
  WebApi/Tasks/Presenters/PullRequestPresenter.cs
  WebApi/Tasks/PullRequestController.cs
Labels: bug

#189 fixed assign labels to pr
  Application/Labels/Commands/Delete/DeleteLabelCommandHandler.cs
  Application/PullRequests/Commands/CreatePullRequest/CreatePullRequestCommandHandler.cs
  Domain/Tasks/Interfaces/IPullRequestRepository.cs
  Domain/Tasks/PullRequest.cs
  Infrastructure/Tasks/PullRequestRepository.cs
  Tests/Integration/Setup/TestDatabaseFactory.cs
  Tests/Unit/PullRequests/CreatePullRequestsUnitTests.cs
  Tests/Unit/PullRequests/MergePullRequestUnitTests.cs
  Tests/Unit/PullRequests/UnassignMilestoneToPullRequestUnitTests.cs
Labels: bug

#194 Added commit and diff preview
  Application/PullRequests/Queries/GetCommitPreview/GetCommitPreviewQuery.cs
  Application/PullRequests/Queries/GetCommitPreview/GetCommitPreviewQueryHandler.cs
  Application/PullRequests/Queries/GetDiffPreview/GetDiffPreviewQuery.cs
  Application/PullRequests/Queries/GetDiffPreview/GetDiffPreviewQueryHandler.cs
  Domain/Shared/Interfaces/IGitService.cs
  Domain/Tasks/Interfaces/IPullRequestRepository.cs
  Infrastructure/Shared/Git/GiteaService.cs
  Infrastructure/Tasks/PullRequestRepository.cs
  WebApi/Tasks/PullRequestController.cs
Labels: enhancement

#197 finished UML diagram to match final model
  UKS-uml-diagram.puml
  UML.png
Labels: documentation
